name: Update README with slides

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        id: node
        run: npm install --frozen-lockfile
        working-directory: scripts

      - name: Install ts-node and typescript
        run: npm install ts-node typescript --save-dev
        working-directory: scripts
        
      - name: Run 
        id: script
        run: npx ts-node updater.ts
        working-directory: scripts
        if: steps.node.outcome == 'success'

      - name: Update readme
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -u README.md
          git commit -m "feat(docs): update readme" || echo "nothing to commit" && true
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}